version: '3'
services:
  python3:
    build: .
    container_name: 'yanai3.10'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    working_dir: '/root/workspace'
    tty: true
    volumes:
      - .:/root/workspace
